version: '3'

networks:
  seongbum_com:
    external: true

volumes:
  ssl:
    external: true

services:
  mail:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mail
    hostname: mail.seongbum.com
    domainname: mail.seongbum.com
    restart: always
    stop_grace_period: 1m
    env_file: ./env/mail.env
    ports:
     - 25:25 # SMTP send
     - 465:465 # ESMTP enforced encryption submission
     - 993:993 # IMAP enforced encryption retrieval
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ssl:/tmp/ssl:ro
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    networks:
      - seongbum_com
